const typeDescriptions = {
  normal: { strong: [], weak: [] },
  normal: { strong: [], weak: [] },
  normal: { strong: [], weak: [] },
  normal: { strong: [], weak: [] },
  normal: { strong: [], weak: [] },
  normal: { strong: [], weak: [] },
  normal: { strong: [], weak: [] },
  normal: { strong: [], weak: [] },
  normal: { strong: [], weak: [] },
  normal: { strong: [], weak: [] },
  normal: { strong: [], weak: [] },
  normal: { strong: [], weak: [] },
  normal: { strong: [], weak: [] },
  normal: { strong: [], weak: [] },
  normal: { strong: [], weak: [] },
  normal: { strong: [], weak: [] },
  normal: { strong: [], weak: [] },
  normal: { strong: [], weak: [] },
};
