const typeDescriptions = {
  normal: { name: "", strong: [], weak: [] },
  fire: { name: "", strong: [], weak: [] },
  water: { name: "", strong: [], weak: [] },
  grass: { name: "", strong: [], weak: [] },
  electric: { name: "", strong: [], weak: [] },
  ice: { name: "", strong: [], weak: [] },
  fighting: { name: "", strong: [], weak: [] },
  poison: { name: "", strong: [], weak: [] },
  ground: { name: "", strong: [], weak: [] },
  flying: { name: "", strong: [], weak: [] },
  psychic: { name: "", strong: [], weak: [] },
  bug: { name: "", strong: [], weak: [] },
  rock: { name: "", strong: [], weak: [] },
  ghost: { name: "", strong: [], weak: [] },
  dragon: { name: "", strong: [], weak: [] },
  dark: { name: "", strong: [], weak: [] },
  steel: { name: "", strong: [], weak: [] },
  fairy: { name: "", strong: [], weak: [] },
};
