const typeDescriptions = {
  normal: {
    name: "normal",
    strong: ["None"],
    weak: ["Rock"],
    no_effect: "Ghost",
  },
  fire: { name: "", strong: [], weak: [], no_effect: "" },
  water: { name: "", strong: [], weak: [], no_effect: "" },
  grass: { name: "", strong: [], weak: [], no_effect: "" },
  electric: { name: "", strong: [], weak: [], no_effect: "" },
  ice: { name: "", strong: [], weak: [], no_effect: "" },
  fighting: { name: "", strong: [], weak: [], no_effect: "" },
  poison: { name: "", strong: [], weak: [], no_effect: "" },
  ground: { name: "", strong: [], weak: [], no_effect: "" },
  flying: { name: "", strong: [], weak: [], no_effect: "" },
  psychic: { name: "", strong: [], weak: [], no_effect: "" },
  bug: { name: "", strong: [], weak: [], no_effect: "" },
  rock: { name: "", strong: [], weak: [], no_effect: "" },
  ghost: { name: "", strong: [], weak: [], no_effect: "" },
  dragon: { name: "", strong: [], weak: [], no_effect: "" },
  dark: { name: "", strong: [], weak: [], no_effect: "" },
  steel: { name: "", strong: [], weak: [], no_effect: "" },
  fairy: { name: "", strong: [], weak: [], no_effect: "" },
};
